### ISSUE TITLE
Urgent installation not working 

### ISSUE THREAD

**Issue by pxh251** [hubmapconsortium/ingest-validation-tools#1056]
Hi,

I used pip install -r requirements.txt to install the validation tool but it still didn't work. Here/s my full code:
(base) H4TGN1F9PN7C:~ hup2$ git clone https://github.com/hubmapconsortium/ingest-validation-tools.git
fatal: destination path 'ingest-validation-tools' already exists and is not an empty directory.
(base) H4TGN1F9PN7C:~ hup2$ cd ingest-validation-tools
(base) H4TGN1F9PN7C:ingest-validation-tools hup2$ pip install -r requirements.txt
Requirement already satisfied: jsonschema==3.2.0 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: pyyaml>=5.3.1 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (6.0)
Requirement already satisfied: frictionless==4.0.0 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (4.0.0)
Requirement already satisfied: yattag==1.14.0 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (1.14.0)
Requirement already satisfied: tableschema-to-template==0.0.11 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (0.0.11)
Requirement already satisfied: requests==2.22.0 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (2.22.0)
Requirement already satisfied: six>=1.11.0 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from jsonschema==3.2.0->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: setuptools in /Users/hup2/miniconda3/lib/python3.9/site-packages (from jsonschema==3.2.0->-r requirements.txt (line 1)) (52.0.0.post20210125)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from jsonschema==3.2.0->-r requirements.txt (line 1)) (0.18.1)
Requirement already satisfied: attrs>=17.4.0 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from jsonschema==3.2.0->-r requirements.txt (line 1)) (21.4.0)
Requirement already satisfied: petl>=1.6 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from frictionless==4.0.0->-r requirements.txt (line 3)) (1.7.8)
Requirement already satisfied: typer[all]>=0.3 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from frictionless==4.0.0->-r requirements.txt (line 3)) (0.4.0)
Requirement already satisfied: chardet>=3.0 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from frictionless==4.0.0->-r requirements.txt (line 3)) (3.0.4)
Requirement already satisfied: stringcase>=1.2 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from frictionless==4.0.0->-r requirements.txt (line 3)) (1.2.0)
Requirement already satisfied: simpleeval>=0.9 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from frictionless==4.0.0->-r requirements.txt (line 3)) (0.9.12)
Requirement already satisfied: validators>=0.18 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from frictionless==4.0.0->-r requirements.txt (line 3)) (0.18.2)
Requirement already satisfied: isodate>=0.6 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from frictionless==4.0.0->-r requirements.txt (line 3)) (0.6.1)
Requirement already satisfied: python-dateutil>=2.8 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from frictionless==4.0.0->-r requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: python-slugify>=1.2 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from frictionless==4.0.0->-r requirements.txt (line 3)) (6.1.1)
Requirement already satisfied: xlsxwriter>=1.2.8 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from tableschema-to-template==0.0.11->-r requirements.txt (line 5)) (3.0.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from requests==2.22.0->-r requirements.txt (line 6)) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from requests==2.22.0->-r requirements.txt (line 6)) (1.25.11)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from requests==2.22.0->-r requirements.txt (line 6)) (2.8)
Requirement already satisfied: text-unidecode>=1.3 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from python-slugify>=1.2->frictionless==4.0.0->-r requirements.txt (line 3)) (1.3)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from typer[all]>=0.3->frictionless==4.0.0->-r requirements.txt (line 3)) (8.0.4)
Requirement already satisfied: shellingham<2.0.0,>=1.3.0 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from typer[all]>=0.3->frictionless==4.0.0->-r requirements.txt (line 3)) (1.4.0)
Requirement already satisfied: colorama<0.5.0,>=0.4.3 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from typer[all]>=0.3->frictionless==4.0.0->-r requirements.txt (line 3)) (0.4.4)
Requirement already satisfied: decorator>=3.4.0 in /Users/hup2/miniconda3/lib/python3.9/site-packages (from validators>=0.18->frictionless==4.0.0->-r requirements.txt (line 3)) (5.1.1)
(base) H4TGN1F9PN7C:ingest-validation-tools hup2$ src/validate_upload.py --help
Traceback (most recent call last):
  File "/Users/hup2/ingest-validation-tools/src/validate_upload.py", line 9, in <module>
    from ingest_validation_tools.error_report import ErrorReport
  File "/Users/hup2/ingest-validation-tools/src/ingest_validation_tools/error_report.py", line 2, in <module>
    from yaml import Dumper, dump
ModuleNotFoundError: No module named 'yaml'
(base) H4TGN1F9PN7C:ingest-validation-tools hup2$ 

The error is the same as last time ( in the last few lines). Since we have to validate and submit data this week, would you mind meet with me via zoom and go through some of the process? I really appreciate that! 

Thank you very much,
Po

**Comment by mccalluc** [comment]
@khanshawPSC will be reaching out.

**Comment by pxh251** [comment]
Hi Chuck,

Thanks for your reply. Do I have to send a separate email to Khan? Or I just wait for his reply?

Thanks,
Po

From: Chuck McCallum ***@***.***>
Reply-To: hubmapconsortium/ingest-validation-tools ***@***.***>
Date: Monday, March 7, 2022 at 4:57 PM
To: hubmapconsortium/ingest-validation-tools ***@***.***>
Cc: "Hu, Po" ***@***.***>, Author ***@***.***>
Subject: [External]Re: [hubmapconsortium/ingest-validation-tools] Urgent installation not working (Issue #1056)


@khanshawPSC<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FkhanshawPSC&data=04%7C01%7Chup2%40chop.edu%7C9598f2088443460b0bb508da0085689b%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637822870249866219%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Mr8WDQHCFvGmD%2FcemkhB7P80i7m0QeMOUV6kFMSeBIQ%3D&reserved=0> will be reaching out.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhubmapconsortium%2Fingest-validation-tools%2Fissues%2F1056%23issuecomment-1061177247&data=04%7C01%7Chup2%40chop.edu%7C9598f2088443460b0bb508da0085689b%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637822870249866219%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0Q10xvIjxIRgUXB96BX%2Fvu%2BMBf3Ed%2BAEE9PS%2Bg5AVwk%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWKF72IEYGXEI6TUCBV2ZVLU6Z3SXANCNFSM5QEO5BAQ&data=04%7C01%7Chup2%40chop.edu%7C9598f2088443460b0bb508da0085689b%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637822870249866219%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ze%2BrcdHDpIustmZO2cLZlvTuPn6SLY1SjNGCJ8BBa6s%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Chup2%40chop.edu%7C9598f2088443460b0bb508da0085689b%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637822870249866219%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e27JRqzn0SKXYHQm6xK9w43x8w2XJurHVSVxp2Ii4bg%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Chup2%40chop.edu%7C9598f2088443460b0bb508da0085689b%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637822870249866219%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OUnoVTBBfbZgK83A7CIYQW9U03fA%2B5ST%2FrEUAjKArP4%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>
** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by khanshawPSC** [comment]
Hello Po (@pxh251). We can get someone to assist with walking you through installing and running the local validation tool. @icaoberg would you have time this week to assist with this?

**Comment by icaoberg** [comment]
@pxh251 do you have time to meet today to figure out why? If so then lmk.

**Comment by pxh251** [comment]
Hi,

Thanks for reaching out. Here’s the output of these pipeline:
[Text  Description automatically generated]

Thanks,
Po

From: icaoberg ***@***.***>
Reply-To: hubmapconsortium/ingest-validation-tools ***@***.***>
Date: Tuesday, March 22, 2022 at 10:18 AM
To: hubmapconsortium/ingest-validation-tools ***@***.***>
Cc: "Hu, Po" ***@***.***>, Mention ***@***.***>
Subject: [External]Re: [hubmapconsortium/ingest-validation-tools] Urgent installation not working (Issue #1056)


@pxh251<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpxh251&data=04%7C01%7Chup2%40chop.edu%7C13213ce2b9244b02e96a08da0c0ed009%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C637835555007298938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9i7dS%2FmjRMNYklynH6dW6dVPoLCgn9oSDw8m8SnjKMo%3D&reserved=0> can you try these and let me know what happens

cd ingest-validation-tools

pip install -r requirements.txt

pip install PyYaml

src/validate_upload.py --help

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhubmapconsortium%2Fingest-validation-tools%2Fissues%2F1056%23issuecomment-1075240922&data=04%7C01%7Chup2%40chop.edu%7C13213ce2b9244b02e96a08da0c0ed009%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C637835555007298938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=L7UrC%2Fg7OsSX8Ia7GzN0kF9l8brIt1IXTrIMHg0LtKk%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWKF72KFNY65LJGBKH3T33DVBHJCVANCNFSM5QEO5BAQ&data=04%7C01%7Chup2%40chop.edu%7C13213ce2b9244b02e96a08da0c0ed009%7Ca611241607b041a59bb1d146b575c975%7C0%7C0%7C637835555007298938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BDat7tCsNVLqYFJImZYFXbU%2Bd5UTNojLYrxiJGHURC8%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by icaoberg** [comment]
@pxh251 what is the output of running the commands? Can you copy it here.
