### ISSUE TITLE
Do we need to change ACLs on Globus to support directory listing?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#110]
Because we need to validate submissions, and because validation can't be run separately from the full ingest pipeline, I've been tasked with trying to get directory listings via the Globus API. [Their demo](https://github.com/globus/native-app-examples) worked out of the box, but changing it to match my client ID and the [HuBMAP Landing Zone UUID](https://app.globus.org/file-manager?origin_id=28bbb03c-a87d-4dd7-a661-7ea2fb6ea631&origin_path=%2F) (just to begin somewhere)
```diff
...
-CLIENT_ID = '1b0dc9d3-0a2b-4000-8bd6-90fb6a79be86'
+CLIENT_ID = '0d7fd5c7-312d-4b9d-9cbc-cd0b0b625be0'
 REDIRECT_URI = 'https://auth.globus.org/v2/web/auth-code'
 SCOPES = ('openid email profile '
           'urn:globus:auth:scope:transfer.api.globus.org:all')

-TUTORIAL_ENDPOINT_ID = 'ddb59aef-6d04-11e5-ba46-22000b92c6ec'
+TUTORIAL_ENDPOINT_ID = '28bbb03c-a87d-4dd7-a661-7ea2fb6ea631'
...
```

produced this error:
```
Traceback (most recent call last):
  File "./example_copy_paste.py", line 65, in <module>
    main()
  File "./example_copy_paste.py", line 60, in main
    for entry in transfer.operation_ls(TUTORIAL_ENDPOINT_ID, path='/~/'):
  File "/opt/anaconda3/envs/ingest/lib/python3.7/site-packages/globus_sdk/transfer/client.py", line 1026, in operation_ls
    return self.get(path, params=params, response_class=IterableTransferResponse)
  File "/opt/anaconda3/envs/ingest/lib/python3.7/site-packages/globus_sdk/base.py", line 234, in get
    retry_401=retry_401,
  File "/opt/anaconda3/envs/ingest/lib/python3.7/site-packages/globus_sdk/base.py", line 553, in _request
    raise self.error_class(r)
globus_sdk.exc.TransferAPIError: (403, 'PermissionDenied', 'No effective ACL rules on the high-assurance endpoint HuBMAP Landing Zone (28bbb03c-a87d-4dd7-a661-7ea2fb6ea631)\nAvailable Identity IDs: c853202e-6018-40b8-beb0-8d37f0f5e14b', '1tJ0wzAo0')
```

I take this to mean that more privs need to be granted on Globus for this to work. (I'm not sure what endpoint ID I should actually be using: Where do the labs assemble their submissions?) (I'm also not sure if I should be making a new application ID, or reusing an old one, if it matters.)

**Comment by mccalluc** [comment]
Not needed: Globus cli is easy to use in subprocess.
