### ISSUE TITLE
FileNotFoundError in windows command line

### ISSUE THREAD

**Issue by mzhou2012** [hubmapconsortium/ingest-validation-tools#1129]
Hello, I am trying to run the validation tool in windows10 using command line tool (I found it won't work in Powershell but works in cmd).
Somehow I keep getting the fileNotFoundError for the example files. I tried a few examples and had the same problem.
I run cmd as admin and still got the same problem. Could anyone give some suggestions to have this run correctly? Thanks!

`C:\Users\***\Downloads\Hubmap_submission\ingest-validation-tools-main>python3 src/validate_upload.py --local_directory examples/dataset-examples/bad-tsv-formats/upload --output as_text
Traceback (most recent call last):
  File "C:\Users\***\Downloads\Hubmap_submission\ingest-validation-tools-main\src\validate_upload.py", line 165, in <module>
    exit_status = main()
  File "C:\Users\***\Downloads\Hubmap_submission\ingest-validation-tools-main\src\validate_upload.py", line 154, in main
    info = upload.get_info()
  File "C:\Users\***\Downloads\Hubmap_submission\ingest-validation-tools-main\src\ingest_validation_tools\upload.py", line 69, in get_info
    git_version = subprocess.check_output(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by sunset666** [comment]
Do you have 'git' installed on your system?

**Comment by mzhou2012** [comment]
> 

No. I just installed it and tried to start by cloning the whole repo, it is working now. Thanks!
I think it will be helpful to make it clear in the "For data submitters and curators:" section that git is required for nerds like me?
Maybe other submitter are also not programmers.
Earlier I simply downloaded the code in zip and put in my folder to run. I only had python3 installed.

**Comment by sunset666** [comment]
it is a good observation to put on somewhere in the instructions
