### ISSUE TITLE
bulkATACseq Validation Broken

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/ingest-validation-tools#1153]
Brendan's Internal Tasking Index Entry: obsidian://open?vault=Brendan%20PSC%20Core&file=20221115%20Fixing%20bulkATACseq%20validation%20-%20broken%20schema

## Problem

Validating a metadata.tsv for a bulkATACseq upload yields the following errors:

> Traceback (most recent call last):
  File "/home/brendan/Documents/ingest-validation-tools/src/validate_tsv.py", line 74, in <module>
    exit_status = main()
  File "/home/brendan/Documents/ingest-validation-tools/src/validate_tsv.py", line 63, in main
    errors = get_tsv_errors(args.path, schema_name=schema_name)
  File "/home/brendan/Documents/ingest-validation-tools/src/ingest_validation_tools/validation_utils.py", line 222, in get_tsv_errors
    return get_table_errors(tsv_path, schema)
  File "/home/brendan/Documents/ingest-validation-tools/src/ingest_validation_tools/table_validator.py", line 26, in get_table_errors
    assert len(report['errors']) == 0, f'report has errors: {report}'
AssertionError: report has errors: {'version': '4.0.0', 'time': 0.009, 'errors': [{'code': 'schema-error', 'name': 'Schema Error', 'tags': ['#general'], 'note': 'constraint "type" is not supported by type "any"', 'message': 'Schema is not valid: constraint "type" is not supported by type "any"', 'description': 'Provided schema is not valid.'}], 'tasks': [], 'stats': {'errors': 1, 'tasks': 0}, 'valid': False}

## Steps Taken Thus Far
- 20221116 - @jswelling and I have discussed how to resolve this. I checked the source YAML files and tested several published ATACseq/SNAREseq (same schema) and bulkATACseq metadata.tsv files. Testing suggests that the above errors are solely from bulkATACseq's schema.

**Comment by bhonick** [comment]
Cayla Mason reached out regarding this on 20230126. BulkATAC is still broken, and I need to test the schema in a few more ways. Ideally, I'll do this between 20230126 and 20230201.
