### ISSUE TITLE
Validation error on AF metadata file

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#206]
None of the Vanderbilt metadata forms have the metadata_path or data_path fields filled with Globus paths because that data is not in Globus yet. The TBD or other substitute entries in these fields have not generated errors for MxIF or MALDI-IMS. However, data_path substitutes appear to be a problem for the AF validation:  

christinebriggs$ src/validate_submission.py --output as_text --type_metadata af:/Users/christinebriggs/dropbox/HMS/INGEST_WORK/IMAGING/AF/VAND_AF_metadata_050320.tsv

Traceback (most recent call last):
  File "src/validate_submission.py", line 148, in <module>
    exit_status = main()
  File "src/validate_submission.py", line 140, in main
    errors = submission.get_errors()
  File "/Users/christinebriggs/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 47, in get_errors
    reference_errors = self._get_reference_errors()
  File "/Users/christinebriggs/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 107, in _get_reference_errors
    multi_ref_errors = self._get_multi_ref_errors()
  File "/Users/christinebriggs/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 127, in _get_multi_ref_errors
    data_references = self._get_data_references()
  File "/Users/christinebriggs/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 139, in _get_data_references
    data_references[row['data_path']].append(reference)
KeyError: 'data_path'

christines-MacBook-Pro:ingest-validation-tools christinebriggs$

Attached as a txt file:

[VAND_AF_metadata_050320.tsv.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/4570966/VAND_AF_metadata_050320.tsv.txt)

**Comment by mccalluc** [comment]
- In the attached file, there is no `data_path` header, instead `metadata_path` is repeated.
- But the stack trace is still bad, and I'll have a fix here soon.
- This comment concerns me:

> The TBD or other substitute entries in these fields have not generated errors for MxIF or MALDI-IMS.

*Please* do not fill in with "TBD" or other substitutes. I will Slack you directly about this.
