### ISSUE TITLE
"can't decode byte 0x9d"

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/ingest-validation-tools#362]
> I have got an error for being unable to decode a byte using the attached tsv file:

```
$ C:\Users\nicog\Downloads\ingest-validation-tools-master\ingest-validation-tools-master> python .\src\validate_samples.py --path C:\Users\nicog\Downloads\seqfish_ingest.tsv

Traceback (most recent call last):
  File ".\src\validate_samples.py", line 48, in <module>
    exit_status = main()
  File ".\src\validate_samples.py", line 40, in main
    errors = samples.get_errors()
  File "C:\Users\nicog\Downloads\ingest-validation-tools-master\ingest-validation-tools-master\src\ingest_validation_tools\samples.py", line 19, in get_errors
    tsv_errors = self._get_tsv_errors()
  File "C:\Users\nicog\Downloads\ingest-validation-tools-master\ingest-validation-tools-master\src\ingest_validation_tools\samples.py", line 27, in _get_tsv_errors
    'sample.yaml').read_text()
  File "C:\Users\nicog\Anaconda3\lib\pathlib.py", line 1179, in read_text
    return f.read()
  File "C:\Users\nicog\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 876: character maps to <undefined>
```

**Comment by mccalluc** [comment]
User error; closing.
