### ISSUE TITLE
validate_submission.py errors after Git Pull

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#538]
Just did git pull & now these errors:

christines-MacBook-Pro:ingest-validation-tools christinebriggs$ src/validate_submission.py --local_directory /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/FAKE_SUBMISSION_DIRECTORY_copy/
Traceback (most recent call last):
  File "src/validate_submission.py", line 9, in <module>
    from ingest_validation_tools.submission import Submission
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 9, in <module>
    from ingest_validation_tools.validation_utils import (
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/validation_utils.py", line 6, in <module>
    from frictionless import validate as validate_table
ModuleNotFoundError: No module named 'frictionless'

**Comment by mccalluc** [comment]
@cebriggs7135 : Run
```
pip install -r requirements.txt
```
We're using a new module, and it needs to be installed. Closing, but ping me on slack if this doesn't work.
