### ISSUE TITLE
validate_submission.py works on sciATACseq.tsv but no longer on CODEX.tsv

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#539]
Attached as txt because tsv not supported here.

christines-MacBook-Pro:ingest-validation-tools christinebriggs$ src/validate_submission.py --local_directory /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/FAKE_SUBMISSION_DIRECTORY/
Traceback (most recent call last):
  File "src/validate_submission.py", line 155, in <module>
    exit_status = main()
  File "src/validate_submission.py", line 147, in main
    errors = submission.get_errors()
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 101, in get_errors
    tsv_errors = self._get_tsv_errors()
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 154, in _get_tsv_errors
    self._get_single_tsv_external_errors(assay_type, path)
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 201, in _get_single_tsv_external_errors
    antibodies_errors = self._get_antibodies_errors(
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 223, in _get_antibodies_errors
    return get_antibodies_errors(antibodies_path,
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/validation_utils.py", line 128, in get_antibodies_errors
    return _get_in_ex_errors(
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/validation_utils.py", line 97, in _get_in_ex_errors
    internal_errors = get_tsv_errors(path, type_name)
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/validation_utils.py", line 157, in get_tsv_errors
    error_messages += [
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/validation_utils.py", line 158, in <listcomp>
    _get_message(error)
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/validation_utils.py", line 182, in _get_message
    f'On row {error["rowPosition"]}, column "{error["fieldName"]}", '
KeyError: 'rowPosition'
christines-MacBook-Pro:ingest-validation-tools christinebriggs$ 

[UFLA_CODEX_TH_metadata.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/5973305/UFLA_CODEX_TH_metadata.txt)

**Comment by mccalluc** [comment]
@cebriggs7135 : Could you update to latest and rerun? I get a normal error message, not what you've pasted. Maybe you've attached the wrong file by mistake?

<details>

```
Metadata TSV Errors:
  /tmp/submission/metadata.tsv (as codex):
    External:
      row 2, referencing /tmp/submission/Data_files_folder:
        No such file or directory: /tmp/submission/Data_files_folder
      row 2, contributors /tmp/submission/contributors.tsv: File does not exist
      row 2, antibodies /tmp/submission/UFLA_antibodies_012921.tsv: File does not
        exist
      row 3, referencing /tmp/submission/Data_files_folder:
        No such file or directory: /tmp/submission/Data_files_folder
      row 3, contributors /tmp/submission/contributors.tsv: File does not exist
      row 3, antibodies /tmp/submission/UFLA_antibodies_012921.tsv: File does not
        exist
      row 4, referencing /tmp/submission/Data_files_folder:
        No such file or directory: /tmp/submission/Data_files_folder
      row 4, contributors /tmp/submission/contributors.tsv: File does not exist
      row 4, antibodies /tmp/submission/UFLA_antibodies_012921.tsv: File does not
        exist
      row 5, referencing /tmp/submission/Data_files_folder:
        No such file or directory: /tmp/submission/Data_files_folder
      row 5, contributors /tmp/submission/contributors.tsv: File does not exist
      row 5, antibodies /tmp/submission/UFLA_antibodies_012921.tsv: File does not
        exist
      row 6, referencing /tmp/submission/Data_files_folder:
        No such file or directory: /tmp/submission/Data_files_folder
      row 6, contributors /tmp/submission/contributors.tsv: File does not exist
      row 6, antibodies /tmp/submission/UFLA_antibodies_012921.tsv: File does not
        exist
      row 7, referencing /tmp/submission/Data_files_folder:
        No such file or directory: /tmp/submission/Data_files_folder
      row 7, contributors /tmp/submission/contributors.tsv: File does not exist
      row 7, antibodies /tmp/submission/UFLA_antibodies_012921.tsv: File does not
        exist
Reference Errors:
  Multiple References:
    ./Data_files_folder:
    - /tmp/submission/metadata.tsv (row 2)
    - /tmp/submission/metadata.tsv (row 3)
    - /tmp/submission/metadata.tsv (row 4)
    - /tmp/submission/metadata.tsv (row 5)
    - /tmp/submission/metadata.tsv (row 6)
    - /tmp/submission/metadata.tsv (row 7)
```

</details>
