### ISSUE TITLE
validate_submission errors for CellDive

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#556]
When validating just the assay metadata tsv, I only get errors for having multiple references to the same data_path. But  validate_submission gets all this:

[[text versions of the metadata files attached:
[GE_CellDive_metadata.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6005679/GE_CellDive_metadata.txt)
[GE_contributors.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6005680/GE_contributors.txt)
[GE_CellDive_antibodies.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6005681/GE_CellDive_antibodies.txt) ]]
christines-MacBook-Pro:ingest-validation-tools christinebriggs$ src/validate_submission.py --local_directory /Users/hristinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/GE_CellDIVE/FAKE_submission/
Traceback (most recent call last):
  File "src/validate_submission.py", line 155, in <module>
    exit_status = main()
  File "src/validate_submission.py", line 147, in main
    errors = submission.get_errors()
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 101, in get_errors
    tsv_errors = self._get_tsv_errors()
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 154, in _get_tsv_errors
    self._get_single_tsv_external_errors(assay_type, path)
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 201, in _get_single_tsv_external_errors
    antibodies_errors = self._get_antibodies_errors(
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 223, in _get_antibodies_errors
    return get_antibodies_errors(antibodies_path,
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/validation_utils.py", line 128, in get_antibodies_errors
    return _get_in_ex_errors(
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/validation_utils.py", line 97, in _get_in_ex_errors
    internal_errors = get_tsv_errors(path, type_name)
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/validation_utils.py", line 157, in get_tsv_errors
    error_messages += [
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/validation_utils.py", line 158, in <listcomp>
    _get_message(error)
  File "/Users/christinebriggs/ingest-validation-tools/ingest-validation-tools/src/ingest_validation_tools/validation_utils.py", line 182, in _get_message
    f'On row {error["rowPosition"]}, column "{error["fieldName"]}", '
KeyError: 'fieldName'
christines-MacBook-Pro:ingest-validation-tools christinebriggs$

**Comment by mccalluc** [comment]
Ok, after #558 is merged, there are still a lot of errors (most of them repeat):
- `On row 49, column "dilution", value " " fails because constraint "pattern" is "1/\d+"` -> whitespace cleaner script should fix this.
- `Row at position "50" is completely blank` -> File an issue if this should be added to the whitespace cleaner.
- `row 3, rr_id: https://scicrunch.org/resolver/RRID:null is 404`
- `row 23, uniprot_accession_number: "https://www.uniprot.org/uniprot/\tP55289 is 404"` -> Bad ID

I also notice that the Antibodies errors are repeated for every row that references them... Let me see if we can just output it once...  filed #559

Once you're updated, let me know if there's anything else for me here.

**Comment by cebriggs7135** [comment]
How do I invoke the whitespace cleaner?

**Comment by mccalluc** [comment]
`src/cleanup_whitespace.py --tsv_path metadata.tsv > clean-metadata.tsv`
