### ISSUE TITLE
validate_submission generates 'schema_name" error message

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/ingest-validation-tools#701]
@mccalluc Has this got something to do with schema not having names anymore?

```
christines-MacBook-Pro:ingest-validation-tools christinebriggs$ src/validate_submission.py --clear_cache --local_directory /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/CALT-UW-proteomics/validation/
Traceback (most recent call last):
  File "src/validate_submission.py", line 165, in <module>
    exit_status = main()
  File "src/validate_submission.py", line 157, in main
    errors = submission.get_errors()
  File "/Users/christinebriggs/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 74, in get_errors
    tsv_errors = self._get_tsv_errors()
  File "/Users/christinebriggs/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 113, in _get_tsv_errors
    types_counter = Counter([v.schema_name for v in self.effective_tsv_paths.values()])
  File "/Users/christinebriggs/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 113, in <listcomp>
    types_counter = Counter([v.schema_name for v in self.effective_tsv_paths.values()])
AttributeError: 'NoneType' object has no attribute 'schema_name'
```

[7f1fd7b9c8c3745fcab037a2fa37f5b9_VAN0003-LK-32_TDMS_metadata.txt](https://github.com/hubmapconsortium/ingest-validation-tools/files/6423446/7f1fd7b9c8c3745fcab037a2fa37f5b9_VAN0003-LK-32_TDMS_metadata.txt)

**Comment by mccalluc** [comment]
@cebriggs7135 -- One problem: There are non-ASCII characters in this data: "1,000-Å pore size"... but it should not error out with a stack trace. Will investigate.

(I would fully support allowing the ingest of properly encoded non-ASCII data, but IEC has said they can't handle it.)

**Comment by mccalluc** [comment]
@cebriggs7135 : Also, can you clarify this comment?
> schema not having names anymore

I'm just not sure which change you are referring to.

**Comment by cebriggs7135** [comment]
@mccalluc I read somewhere in Slack or here something your wrote about how schemas would not have names, only assays would?

**Comment by mccalluc** [comment]
> @mccalluc I read somewhere in Slack or here something your wrote about how schemas would not have names, only assays would?

That is only about the titles of pages on github. There is no change to validation behavior.

**Comment by cebriggs7135** [comment]
Good to know.

**Comment by cebriggs7135** [comment]
@mccalluc I added the version column because that was missing but get the same error message: 

""christines-MacBook-Pro:ingest-validation-tools christinebriggs$ src/validate_submission.py --clear_cache --tsv_paths /Users/christinebriggs/dropbox/HMS/INGEST_WORK/RELEASE2_DOCS/CALT-UW-proteomics//validation/metadata.tsv 
Traceback (most recent call last):
  File "src/validate_submission.py", line 165, in <module>
    exit_status = main()
  File "src/validate_submission.py", line 157, in main
    errors = submission.get_errors()
  File "/Users/christinebriggs/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 74, in get_errors
    tsv_errors = self._get_tsv_errors()
  File "/Users/christinebriggs/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 113, in _get_tsv_errors
    types_counter = Counter([v.schema_name for v in self.effective_tsv_paths.values()])
  File "/Users/christinebriggs/ingest-validation-tools/src/ingest_validation_tools/submission.py", line 113, in <listcomp>
    types_counter = Counter([v.schema_name for v in self.effective_tsv_paths.values()])
AttributeError: 'NoneType' object has no attribute 'schema_name'""

**Comment by mccalluc** [comment]
@cebriggs7135 -- Behavior will not change until you approve #702 and it is merged.
