### ISSUE TITLE
en dashes "–" in "description" portion of metadata .tsv cause AttributeError, crashing validation tool 

### ISSUE THREAD

**Issue by NHPatterson** [hubmapconsortium/ingest-validation-tools#706]
Hi all,

I have an assay description in the `description` tag of the af-metadata.tsv (https://hubmapconsortium.github.io/ingest-validation-tools/af/):
"... Autofluorescence images were collected with a Carl Zeiss microscopy AxioScan.Z1 using 3 channels/filters – DAPI (excitation: 335-383 nm/emission: 420-470 nm), eGFP (excitation: 450-490 nm/emission: 500-550 nm), and dsRed (excitation: 538-562 nm/emission: 570-640 nm) ..."

Raises this error:
```python
Traceback (most recent call last):
  File "src/validate_submission.py", line 165, in <module>
    exit_status = main()
  File "src/validate_submission.py", line 157, in main
    errors = submission.get_errors()
  File "U:\Heath\ingest-val\ingest-validation-tools\src\ingest_validation_tools\submission.py", line 74, in get_errors
    tsv_errors = self._get_tsv_errors()
  File "U:\Heath\ingest-val\ingest-validation-tools\src\ingest_validation_tools\submission.py", line 113, in _get_tsv_errors
    types_counter = Counter([v.schema_name for v in self.effective_tsv_paths.values()])
  File "U:\Heath\ingest-val\ingest-validation-tools\src\ingest_validation_tools\submission.py", line 113, in <listcomp>
    types_counter = Counter([v.schema_name for v in self.effective_tsv_paths.values()])
AttributeError: 'NoneType' object has no attribute 'schema_name'
```

I can fix this by using short dashes, but given the free-form text field nature of this, handling special characters could be helpful to avoid this ambiguous errors.

**Comment by mccalluc** [comment]
If you upgrade to the latest, the error message will at least be cleaner. (Improved by #702)

... But it would still be an error. Last I checked, the downstream database was not able to handle non-ascii characters. @jswelling : Is that still correct?
